from .employees.list import employee_list
from .employees.form import employee_form
from .departments.list import department_list
from .departments.details import department_details
from .departments.form import department_form
from .home import home
from .auth.logout import logout_user
from .trainingprograms.list import training_program_list
from .trainingprograms.form import training_form
from .trainingprograms.form import training_edit_form
from .trainingprograms.details import program_details
from .computers.list import computer_list
from .computers.form import computer_form
from .computers.details import computer_details
